spring.application.name=auth-service
server.port=${AUTH_SERVICE_PORT:8082}

logging.level.root=INFO
logging.level.com.microecommerce.auth=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always

auth.google.issuer=https://accounts.google.com
auth.google.client-id=${GOOGLE_CLIENT_ID:771350731161-kkn1m7u0g7g8d7ac8aqu6iubqjltnbo1.apps.googleusercontent.com}

auth.jwt.secret=${AUTH_JWT_SECRET:change-this-secret-key-to-at-least-32-bytes-long}
auth.jwt.expiration-seconds=${AUTH_JWT_EXPIRATION_SECONDS:3600}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000}
